package com.xoa.model.chatList;

import com.xoa.model.base.PageModel;

import java.util.Date;

public class ChatList extends PageModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.from_id
     *
     * @mbggenerated
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.from_name
     *
     * @mbggenerated
     */
    private String fromName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.to_id
     *
     * @mbggenerated
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.to_name
     *
     * @mbggenerated
     */
    private String toName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_list.last_content
     *
     * @mbggenerated
     */
    private String lastContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.id
     *
     * @return the value of chat_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.id
     *
     * @param id the value for chat_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.from_id
     *
     * @return the value of chat_list.from_id
     *
     * @mbggenerated
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.from_id
     *
     * @param fromId the value for chat_list.from_id
     *
     * @mbggenerated
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.from_name
     *
     * @return the value of chat_list.from_name
     *
     * @mbggenerated
     */
    public String getFromName() {
        return fromName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.from_name
     *
     * @param fromName the value for chat_list.from_name
     *
     * @mbggenerated
     */
    public void setFromName(String fromName) {
        this.fromName = fromName == null ? null : fromName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.to_id
     *
     * @return the value of chat_list.to_id
     *
     * @mbggenerated
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.to_id
     *
     * @param toId the value for chat_list.to_id
     *
     * @mbggenerated
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.to_name
     *
     * @return the value of chat_list.to_name
     *
     * @mbggenerated
     */
    public String getToName() {
        return toName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.to_name
     *
     * @param toName the value for chat_list.to_name
     *
     * @mbggenerated
     */
    public void setToName(String toName) {
        this.toName = toName == null ? null : toName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.create_time
     *
     * @return the value of chat_list.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.create_time
     *
     * @param createTime the value for chat_list.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.end_time
     *
     * @return the value of chat_list.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.end_time
     *
     * @param endTime the value for chat_list.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.update_time
     *
     * @return the value of chat_list.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.update_time
     *
     * @param updateTime the value for chat_list.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.type
     *
     * @return the value of chat_list.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.type
     *
     * @param type the value for chat_list.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_list.last_content
     *
     * @return the value of chat_list.last_content
     *
     * @mbggenerated
     */
    public String getLastContent() {
        return lastContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_list.last_content
     *
     * @param lastContent the value for chat_list.last_content
     *
     * @mbggenerated
     */
    public void setLastContent(String lastContent) {
        this.lastContent = lastContent == null ? null : lastContent.trim();
    }


}