package com.xoa.model.doctor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DoctorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public DoctorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andBrithDateIsNull() {
            addCriterion("brith_date is null");
            return (Criteria) this;
        }

        public Criteria andBrithDateIsNotNull() {
            addCriterion("brith_date is not null");
            return (Criteria) this;
        }

        public Criteria andBrithDateEqualTo(String value) {
            addCriterion("brith_date =", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateNotEqualTo(String value) {
            addCriterion("brith_date <>", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateGreaterThan(String value) {
            addCriterion("brith_date >", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateGreaterThanOrEqualTo(String value) {
            addCriterion("brith_date >=", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateLessThan(String value) {
            addCriterion("brith_date <", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateLessThanOrEqualTo(String value) {
            addCriterion("brith_date <=", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateLike(String value) {
            addCriterion("brith_date like", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateNotLike(String value) {
            addCriterion("brith_date not like", value, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateIn(List<String> values) {
            addCriterion("brith_date in", values, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateNotIn(List<String> values) {
            addCriterion("brith_date not in", values, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateBetween(String value1, String value2) {
            addCriterion("brith_date between", value1, value2, "brithDate");
            return (Criteria) this;
        }

        public Criteria andBrithDateNotBetween(String value1, String value2) {
            addCriterion("brith_date not between", value1, value2, "brithDate");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andMindTotalIsNull() {
            addCriterion("mind_total is null");
            return (Criteria) this;
        }

        public Criteria andMindTotalIsNotNull() {
            addCriterion("mind_total is not null");
            return (Criteria) this;
        }

        public Criteria andMindTotalEqualTo(Integer value) {
            addCriterion("mind_total =", value, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalNotEqualTo(Integer value) {
            addCriterion("mind_total <>", value, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalGreaterThan(Integer value) {
            addCriterion("mind_total >", value, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("mind_total >=", value, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalLessThan(Integer value) {
            addCriterion("mind_total <", value, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalLessThanOrEqualTo(Integer value) {
            addCriterion("mind_total <=", value, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalIn(List<Integer> values) {
            addCriterion("mind_total in", values, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalNotIn(List<Integer> values) {
            addCriterion("mind_total not in", values, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalBetween(Integer value1, Integer value2) {
            addCriterion("mind_total between", value1, value2, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andMindTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("mind_total not between", value1, value2, "mindTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalIsNull() {
            addCriterion("consult_total is null");
            return (Criteria) this;
        }

        public Criteria andConsultTotalIsNotNull() {
            addCriterion("consult_total is not null");
            return (Criteria) this;
        }

        public Criteria andConsultTotalEqualTo(Integer value) {
            addCriterion("consult_total =", value, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalNotEqualTo(Integer value) {
            addCriterion("consult_total <>", value, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalGreaterThan(Integer value) {
            addCriterion("consult_total >", value, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("consult_total >=", value, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalLessThan(Integer value) {
            addCriterion("consult_total <", value, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalLessThanOrEqualTo(Integer value) {
            addCriterion("consult_total <=", value, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalIn(List<Integer> values) {
            addCriterion("consult_total in", values, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalNotIn(List<Integer> values) {
            addCriterion("consult_total not in", values, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalBetween(Integer value1, Integer value2) {
            addCriterion("consult_total between", value1, value2, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andConsultTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("consult_total not between", value1, value2, "consultTotal");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(Integer value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(Integer value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(Integer value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(Integer value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(Integer value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<Integer> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<Integer> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(Integer value1, Integer value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(Integer value1, Integer value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andHospitalIsNull() {
            addCriterion("hospital is null");
            return (Criteria) this;
        }

        public Criteria andHospitalIsNotNull() {
            addCriterion("hospital is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalEqualTo(String value) {
            addCriterion("hospital =", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalNotEqualTo(String value) {
            addCriterion("hospital <>", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalGreaterThan(String value) {
            addCriterion("hospital >", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalGreaterThanOrEqualTo(String value) {
            addCriterion("hospital >=", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalLessThan(String value) {
            addCriterion("hospital <", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalLessThanOrEqualTo(String value) {
            addCriterion("hospital <=", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalLike(String value) {
            addCriterion("hospital like", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalNotLike(String value) {
            addCriterion("hospital not like", value, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalIn(List<String> values) {
            addCriterion("hospital in", values, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalNotIn(List<String> values) {
            addCriterion("hospital not in", values, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalBetween(String value1, String value2) {
            addCriterion("hospital between", value1, value2, "hospital");
            return (Criteria) this;
        }

        public Criteria andHospitalNotBetween(String value1, String value2) {
            addCriterion("hospital not between", value1, value2, "hospital");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andHeadPictureIsNull() {
            addCriterion("head_picture is null");
            return (Criteria) this;
        }

        public Criteria andHeadPictureIsNotNull() {
            addCriterion("head_picture is not null");
            return (Criteria) this;
        }

        public Criteria andHeadPictureEqualTo(String value) {
            addCriterion("head_picture =", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotEqualTo(String value) {
            addCriterion("head_picture <>", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureGreaterThan(String value) {
            addCriterion("head_picture >", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureGreaterThanOrEqualTo(String value) {
            addCriterion("head_picture >=", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureLessThan(String value) {
            addCriterion("head_picture <", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureLessThanOrEqualTo(String value) {
            addCriterion("head_picture <=", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureLike(String value) {
            addCriterion("head_picture like", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotLike(String value) {
            addCriterion("head_picture not like", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureIn(List<String> values) {
            addCriterion("head_picture in", values, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotIn(List<String> values) {
            addCriterion("head_picture not in", values, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureBetween(String value1, String value2) {
            addCriterion("head_picture between", value1, value2, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotBetween(String value1, String value2) {
            addCriterion("head_picture not between", value1, value2, "headPicture");
            return (Criteria) this;
        }

        public Criteria andIdfStateIsNull() {
            addCriterion("idf_state is null");
            return (Criteria) this;
        }

        public Criteria andIdfStateIsNotNull() {
            addCriterion("idf_state is not null");
            return (Criteria) this;
        }

        public Criteria andIdfStateEqualTo(Integer value) {
            addCriterion("idf_state =", value, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateNotEqualTo(Integer value) {
            addCriterion("idf_state <>", value, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateGreaterThan(Integer value) {
            addCriterion("idf_state >", value, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("idf_state >=", value, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateLessThan(Integer value) {
            addCriterion("idf_state <", value, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateLessThanOrEqualTo(Integer value) {
            addCriterion("idf_state <=", value, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateIn(List<Integer> values) {
            addCriterion("idf_state in", values, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateNotIn(List<Integer> values) {
            addCriterion("idf_state not in", values, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateBetween(Integer value1, Integer value2) {
            addCriterion("idf_state between", value1, value2, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfStateNotBetween(Integer value1, Integer value2) {
            addCriterion("idf_state not between", value1, value2, "idfState");
            return (Criteria) this;
        }

        public Criteria andIdfBasisIsNull() {
            addCriterion("idf_basis is null");
            return (Criteria) this;
        }

        public Criteria andIdfBasisIsNotNull() {
            addCriterion("idf_basis is not null");
            return (Criteria) this;
        }

        public Criteria andIdfBasisEqualTo(String value) {
            addCriterion("idf_basis =", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisNotEqualTo(String value) {
            addCriterion("idf_basis <>", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisGreaterThan(String value) {
            addCriterion("idf_basis >", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisGreaterThanOrEqualTo(String value) {
            addCriterion("idf_basis >=", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisLessThan(String value) {
            addCriterion("idf_basis <", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisLessThanOrEqualTo(String value) {
            addCriterion("idf_basis <=", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisLike(String value) {
            addCriterion("idf_basis like", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisNotLike(String value) {
            addCriterion("idf_basis not like", value, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisIn(List<String> values) {
            addCriterion("idf_basis in", values, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisNotIn(List<String> values) {
            addCriterion("idf_basis not in", values, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisBetween(String value1, String value2) {
            addCriterion("idf_basis between", value1, value2, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andIdfBasisNotBetween(String value1, String value2) {
            addCriterion("idf_basis not between", value1, value2, "idfBasis");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailIsNull() {
            addCriterion("adept_detail is null");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailIsNotNull() {
            addCriterion("adept_detail is not null");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailEqualTo(String value) {
            addCriterion("adept_detail =", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailNotEqualTo(String value) {
            addCriterion("adept_detail <>", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailGreaterThan(String value) {
            addCriterion("adept_detail >", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailGreaterThanOrEqualTo(String value) {
            addCriterion("adept_detail >=", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailLessThan(String value) {
            addCriterion("adept_detail <", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailLessThanOrEqualTo(String value) {
            addCriterion("adept_detail <=", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailLike(String value) {
            addCriterion("adept_detail like", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailNotLike(String value) {
            addCriterion("adept_detail not like", value, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailIn(List<String> values) {
            addCriterion("adept_detail in", values, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailNotIn(List<String> values) {
            addCriterion("adept_detail not in", values, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailBetween(String value1, String value2) {
            addCriterion("adept_detail between", value1, value2, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andAdeptDetailNotBetween(String value1, String value2) {
            addCriterion("adept_detail not between", value1, value2, "adeptDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailIsNull() {
            addCriterion("info_detail is null");
            return (Criteria) this;
        }

        public Criteria andInfoDetailIsNotNull() {
            addCriterion("info_detail is not null");
            return (Criteria) this;
        }

        public Criteria andInfoDetailEqualTo(String value) {
            addCriterion("info_detail =", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailNotEqualTo(String value) {
            addCriterion("info_detail <>", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailGreaterThan(String value) {
            addCriterion("info_detail >", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailGreaterThanOrEqualTo(String value) {
            addCriterion("info_detail >=", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailLessThan(String value) {
            addCriterion("info_detail <", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailLessThanOrEqualTo(String value) {
            addCriterion("info_detail <=", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailLike(String value) {
            addCriterion("info_detail like", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailNotLike(String value) {
            addCriterion("info_detail not like", value, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailIn(List<String> values) {
            addCriterion("info_detail in", values, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailNotIn(List<String> values) {
            addCriterion("info_detail not in", values, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailBetween(String value1, String value2) {
            addCriterion("info_detail between", value1, value2, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andInfoDetailNotBetween(String value1, String value2) {
            addCriterion("info_detail not between", value1, value2, "infoDetail");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeIsNull() {
            addCriterion("online_time is null");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeIsNotNull() {
            addCriterion("online_time is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeEqualTo(String value) {
            addCriterion("online_time =", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeNotEqualTo(String value) {
            addCriterion("online_time <>", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeGreaterThan(String value) {
            addCriterion("online_time >", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeGreaterThanOrEqualTo(String value) {
            addCriterion("online_time >=", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeLessThan(String value) {
            addCriterion("online_time <", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeLessThanOrEqualTo(String value) {
            addCriterion("online_time <=", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeLike(String value) {
            addCriterion("online_time like", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeNotLike(String value) {
            addCriterion("online_time not like", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeIn(List<String> values) {
            addCriterion("online_time in", values, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeNotIn(List<String> values) {
            addCriterion("online_time not in", values, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeBetween(String value1, String value2) {
            addCriterion("online_time between", value1, value2, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeNotBetween(String value1, String value2) {
            addCriterion("online_time not between", value1, value2, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationIsNull() {
            addCriterion("evaluation is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationIsNotNull() {
            addCriterion("evaluation is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationEqualTo(Integer value) {
            addCriterion("evaluation =", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationNotEqualTo(Integer value) {
            addCriterion("evaluation <>", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationGreaterThan(Integer value) {
            addCriterion("evaluation >", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationGreaterThanOrEqualTo(Integer value) {
            addCriterion("evaluation >=", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationLessThan(Integer value) {
            addCriterion("evaluation <", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationLessThanOrEqualTo(Integer value) {
            addCriterion("evaluation <=", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationIn(List<Integer> values) {
            addCriterion("evaluation in", values, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationNotIn(List<Integer> values) {
            addCriterion("evaluation not in", values, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationBetween(Integer value1, Integer value2) {
            addCriterion("evaluation between", value1, value2, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationNotBetween(Integer value1, Integer value2) {
            addCriterion("evaluation not between", value1, value2, "evaluation");
            return (Criteria) this;
        }

        public Criteria andQrCodeIsNull() {
            addCriterion("qr_code is null");
            return (Criteria) this;
        }

        public Criteria andQrCodeIsNotNull() {
            addCriterion("qr_code is not null");
            return (Criteria) this;
        }

        public Criteria andQrCodeEqualTo(String value) {
            addCriterion("qr_code =", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotEqualTo(String value) {
            addCriterion("qr_code <>", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeGreaterThan(String value) {
            addCriterion("qr_code >", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("qr_code >=", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeLessThan(String value) {
            addCriterion("qr_code <", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeLessThanOrEqualTo(String value) {
            addCriterion("qr_code <=", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeLike(String value) {
            addCriterion("qr_code like", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotLike(String value) {
            addCriterion("qr_code not like", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeIn(List<String> values) {
            addCriterion("qr_code in", values, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotIn(List<String> values) {
            addCriterion("qr_code not in", values, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeBetween(String value1, String value2) {
            addCriterion("qr_code between", value1, value2, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotBetween(String value1, String value2) {
            addCriterion("qr_code not between", value1, value2, "qrCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}