package com.xoa.model.doctor;

import com.xoa.model.base.PageModel;

import java.util.Date;

public class Doctor extends PageModel {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.id
     *
     * @mbggenerated

     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.name
     *
     * @mbggenerated
     */
    private String name;

    private String searchText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.brith_date
     *
     * @mbggenerated
     */
    private String brithDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.mind_total
     *
     * @mbggenerated
     */
    private Float mindTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.consult_total
     *
     * @mbggenerated
     */
    private Float consultTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.balance
     *
     * @mbggenerated
     */
    private Float balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.hospital
     *
     * @mbggenerated
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.title
     *
     * @mbggenerated
     */
    private String title;

    private String department;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.head_picture
     *
     * @mbggenerated
     */
    private String headPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.idf_state
     *
     * @mbggenerated
     */
    private Integer idfState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.idf_basis
     *
     * @mbggenerated
     */
    private String idfBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.adept_detail
     *
     * @mbggenerated
     */
    private String skillful;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.info_detail
     *
     * @mbggenerated
     */
    private String infoDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.online_time
     *
     * @mbggenerated
     */
    private String onlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.evaluation
     *
     * @mbggenerated
     */
    private Integer evaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.qr_code
     *
     * @mbggenerated
     */
    private String qrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.id
     *
     * @return the value of doctor_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.id
     *
     * @param id the value for doctor_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.name
     *
     * @return the value of doctor_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.name
     *
     * @param name the value for doctor_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.gender
     *
     * @return the value of doctor_info.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.gender
     *
     * @param gender the value for doctor_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.brith_date
     *
     * @return the value of doctor_info.brith_date
     *
     * @mbggenerated
     */
    public String getBrithDate() {
        return brithDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.brith_date
     *
     * @param brithDate the value for doctor_info.brith_date
     *
     * @mbggenerated
     */
    public void setBrithDate(String brithDate) {
        this.brithDate = brithDate == null ? null : brithDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.tel
     *
     * @return the value of doctor_info.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.tel
     *
     * @param tel the value for doctor_info.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.mind_total
     *
     * @return the value of doctor_info.mind_total
     *
     * @mbggenerated
     */
    public Float getMindTotal() {
        return mindTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.mind_total
     *
     * @param mindTotal the value for doctor_info.mind_total
     *
     * @mbggenerated
     */
    public void setMindTotal(Float mindTotal) {
        this.mindTotal = mindTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.consult_total
     *
     * @return the value of doctor_info.consult_total
     *
     * @mbggenerated
     */
    public Float getConsultTotal() {
        return consultTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.consult_total
     *
     * @param consultTotal the value for doctor_info.consult_total
     *
     * @mbggenerated
     */
    public void setConsultTotal(Float consultTotal) {
        this.consultTotal = consultTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.balance
     *
     * @return the value of doctor_info.balance
     *
     * @mbggenerated
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.balance
     *
     * @param balance the value for doctor_info.balance
     *
     * @mbggenerated
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.hospital
     *
     * @return the value of doctor_info.hospital
     *
     * @mbggenerated
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.hospital
     *
     * @param hospital the value for doctor_info.hospital
     *
     * @mbggenerated
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.title
     *
     * @return the value of doctor_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.title
     *
     * @param title the value for doctor_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.head_picture
     *
     * @return the value of doctor_info.head_picture
     *
     * @mbggenerated
     */
    public String getHeadPicture() {
        return headPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.head_picture
     *
     * @param headPicture the value for doctor_info.head_picture
     *
     * @mbggenerated
     */
    public void setHeadPicture(String headPicture) {
        this.headPicture = headPicture == null ? null : headPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.idf_state
     *
     * @return the value of doctor_info.idf_state
     *
     * @mbggenerated
     */
    public Integer getIdfState() {
        return idfState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.idf_state
     *
     * @param idfState the value for doctor_info.idf_state
     *
     * @mbggenerated
     */
    public void setIdfState(Integer idfState) {
        this.idfState = idfState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.idf_basis
     *
     * @return the value of doctor_info.idf_basis
     *
     * @mbggenerated
     */
    public String getIdfBasis() {
        return idfBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.idf_basis
     *
     * @param idfBasis the value for doctor_info.idf_basis
     *
     * @mbggenerated
     */
    public void setIdfBasis(String idfBasis) {
        this.idfBasis = idfBasis == null ? null : idfBasis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.adept_detail
     *
     * @return the value of doctor_info.adept_detail
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.info_detail
     *
     * @return the value of doctor_info.info_detail
     *
     * @mbggenerated
     */
    public String getInfoDetail() {
        return infoDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.info_detail
     *
     * @param infoDetail the value for doctor_info.info_detail
     *
     * @mbggenerated
     */
    public void setInfoDetail(String infoDetail) {
        this.infoDetail = infoDetail == null ? null : infoDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.online_time
     *
     * @return the value of doctor_info.online_time
     *
     * @mbggenerated
     */
    public String getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.online_time
     *
     * @param onlineTime the value for doctor_info.online_time
     *
     * @mbggenerated
     */
    public void setOnlineTime(String onlineTime) {
        this.onlineTime = onlineTime == null ? null : onlineTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.evaluation
     *
     * @return the value of doctor_info.evaluation
     *
     * @mbggenerated
     */
    public Integer getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.evaluation
     *
     * @param evaluation the value for doctor_info.evaluation
     *
     * @mbggenerated
     */
    public void setEvaluation(Integer evaluation) {
        this.evaluation = evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.qr_code
     *
     * @return the value of doctor_info.qr_code
     *
     * @mbggenerated
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.qr_code
     *
     * @param qrCode the value for doctor_info.qr_code
     *
     * @mbggenerated
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.create_time
     *
     * @return the value of doctor_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.create_time
     *
     * @param createTime the value for doctor_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.update_time
     *
     * @return the value of doctor_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.update_time
     *
     * @param updateTime the value for doctor_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getSkillful() {
        return skillful;
    }

    public void setSkillful(String skillful) {
        this.skillful = skillful;
    }

    public String getSearchText() {
        return searchText;
    }

    public void setSearchText(String searchText) {
        this.searchText = searchText;
    }
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }
}