package com.xoa.model.WeChatUserMappingModel;

import java.util.Date;

public class WeChatUserMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxusermapping.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxusermapping.mainId
     *
     * @mbggenerated
     */
    private String mainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxusermapping.toid
     *
     * @mbggenerated
     */
    private String toid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxusermapping.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxusermapping.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxusermapping.id
     *
     * @return the value of wxusermapping.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxusermapping.id
     *
     * @param id the value for wxusermapping.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxusermapping.mainId
     *
     * @return the value of wxusermapping.mainId
     *
     * @mbggenerated
     */
    public String getMainid() {
        return mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxusermapping.mainId
     *
     * @param mainid the value for wxusermapping.mainId
     *
     * @mbggenerated
     */
    public void setMainid(String mainid) {
        this.mainid = mainid == null ? null : mainid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxusermapping.toid
     *
     * @return the value of wxusermapping.toid
     *
     * @mbggenerated
     */
    public String getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxusermapping.toid
     *
     * @param toid the value for wxusermapping.toid
     *
     * @mbggenerated
     */
    public void setToid(String toid) {
        this.toid = toid == null ? null : toid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxusermapping.date
     *
     * @return the value of wxusermapping.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxusermapping.date
     *
     * @param date the value for wxusermapping.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxusermapping.type
     *
     * @return the value of wxusermapping.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxusermapping.type
     *
     * @param type the value for wxusermapping.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}