package com.xoa.dao.wxUser;

import com.xoa.model.wxUser.wxUser;
import com.xoa.model.wxUser.wxUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface wxUserMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated
     */
    int insert(wxUser wxuser);

    int updateByPrimaryKey(wxUser wxuser);

    wxUser selectByOpenId(String openid);


}