package com.xoa.dao.chatDetail;

import com.xoa.model.chatDetail.chatDetail;
import com.xoa.model.chatDetail.chatDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface chatDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int countByExample(chatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int deleteByExample(chatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int insert(chatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int insertSelective(chatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    List<chatDetail> selectByExample(chatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    chatDetail selectByPrimaryKey(Integer id);

    List<chatDetail> selectBySessionId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") chatDetail record, @Param("example") chatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") chatDetail record, @Param("example") chatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(chatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(chatDetail record);
}