package com.xoa.model.chatDetail;

import java.util.Date;

public class chatDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.session_id
     *
     * @mbggenerated
     */
    private Integer sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.from_id
     *
     * @mbggenerated
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.to_id
     *
     * @mbggenerated
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.from_type
     *
     * @mbggenerated
     */
    private String fromType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.filed_url
     *
     * @mbggenerated
     */
    private String filedUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.file_content
     *
     * @mbggenerated
     */
    private String fileContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.send_time
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.accept_time
     *
     * @mbggenerated
     */
    private Date acceptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_detail.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.id
     *
     * @return the value of chat_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.id
     *
     * @param id the value for chat_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.session_id
     *
     * @return the value of chat_detail.session_id
     *
     * @mbggenerated
     */
    public Integer getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.session_id
     *
     * @param sessionId the value for chat_detail.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.from_id
     *
     * @return the value of chat_detail.from_id
     *
     * @mbggenerated
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.from_id
     *
     * @param fromId the value for chat_detail.from_id
     *
     * @mbggenerated
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.to_id
     *
     * @return the value of chat_detail.to_id
     *
     * @mbggenerated
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.to_id
     *
     * @param toId the value for chat_detail.to_id
     *
     * @mbggenerated
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.from_type
     *
     * @return the value of chat_detail.from_type
     *
     * @mbggenerated
     */
    public String getFromType() {
        return fromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.from_type
     *
     * @param fromType the value for chat_detail.from_type
     *
     * @mbggenerated
     */
    public void setFromType(String fromType) {
        this.fromType = fromType == null ? null : fromType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.content
     *
     * @return the value of chat_detail.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.content
     *
     * @param content the value for chat_detail.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.filed_url
     *
     * @return the value of chat_detail.filed_url
     *
     * @mbggenerated
     */
    public String getFiledUrl() {
        return filedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.filed_url
     *
     * @param filedUrl the value for chat_detail.filed_url
     *
     * @mbggenerated
     */
    public void setFiledUrl(String filedUrl) {
        this.filedUrl = filedUrl == null ? null : filedUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.file_content
     *
     * @return the value of chat_detail.file_content
     *
     * @mbggenerated
     */
    public String getFileContent() {
        return fileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.file_content
     *
     * @param fileContent the value for chat_detail.file_content
     *
     * @mbggenerated
     */
    public void setFileContent(String fileContent) {
        this.fileContent = fileContent == null ? null : fileContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.type
     *
     * @return the value of chat_detail.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.type
     *
     * @param type the value for chat_detail.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.send_time
     *
     * @return the value of chat_detail.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.send_time
     *
     * @param sendTime the value for chat_detail.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.accept_time
     *
     * @return the value of chat_detail.accept_time
     *
     * @mbggenerated
     */
    public Date getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.accept_time
     *
     * @param acceptTime the value for chat_detail.accept_time
     *
     * @mbggenerated
     */
    public void setAcceptTime(Date acceptTime) {
        this.acceptTime = acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_detail.is_delete
     *
     * @return the value of chat_detail.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_detail.is_delete
     *
     * @param isDelete the value for chat_detail.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}